[build]
  base = "apps/web"
  command = "cd apps/web && npm install"
  publish = "apps/web"
  functions = "apps/web/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/form"
  to = "/#cta"
  status = 302

[[redirects]]
  from = "/waitlist"
  to = "/#cta"
  status = 302

# Serve index.html for all routes (SPA behavior)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"